import type { Metadata } from 'next';
export const metadata: Metadata = { alternates: { canonical: '/' } };
import { ArrowDown, ArrowUpRight, Asterisk } from 'lucide-react';
import { Navigation } from '@/components/navigation';
import { ProjectGallery } from '@/components/project-gallery';
import { Services } from '@/components/services';
import { Growth } from '@/components/growth';
import { BrandMark } from '@/components/brand-mark';
import { SystemMark } from '@/components/system-mark';
import { site } from '@/lib/site';
import { Motion } from '@/components/motion';
import { Footer } from '@/components/footer';

export default function Home() { return <><Navigation/><main>
  <section className="hero" id="top"><div className="hero-atmosphere" aria-hidden="true"><div className="hero-orb"/></div><div className="hero-meta"><span>INDEPENDENT CREATIVE STUDIO</span><span>BASED IN MUNICH / WORKING EVERYWHERE</span></div><div className="hero-body"><p className="hero-kicker"><Asterisk size={18}/> STRATEGY · DESIGN · CONTENT</p><h1>Built to be<br/><span><em>remembered.</em></span></h1><div className="hero-bottom"><p>Strategie, Design und Content für Marken, die im Gedächtnis bleiben.</p></div></div><div className="hero-foot"><span>LL COLLECTIVE STUDIO © {new Date().getFullYear()}</span><a href="#intro" aria-label="Zum nächsten Abschnitt scrollen">SCROLL TO EXPLORE <ArrowDown size={15}/></a><span>01 / 06</span></div></section>
  <section id="intro" className="intro-section section-pad"><div className="intro-top"><span className="eyebrow">A NOTE FROM THE STUDIO</span><span>01 — 06</span></div><p className="intro-statement reveal">Gute Marken entstehen durch <em>eine klare Richtung.</em> Wir verbinden Strategie, Design und Content zu einem Auftritt, der <span>verstanden und erinnert</span> wird.</p><div className="intro-bottom"><span className="intro-symbol"><BrandMark large/></span><p>LL Collective Studio ist ein unabhängiges Kreativstudio aus dem Raum München. Persönlich in der Zusammenarbeit. Präzise in der Idee. Mutig in der Umsetzung.</p></div></section>
  <ProjectGallery/><Services/><Growth/>
  <section id="about" className="about-section section-pad"><div className="about-heading"><span className="eyebrow">04 / THE PEOPLE BEHIND IT</span><h2>Two perspectives.<br/><em>One collective.</em></h2></div><div className="about-content"><div className="about-visual"><div className="about-visual-top"><span>LL COLLECTIVE</span><span>STUDIO / 04</span></div><SystemMark/><div className="about-visual-caption">TWO MINDS. ONE DIRECTION.<br/>MUNICH / GERMANY</div></div><div className="about-copy"><span className="eyebrow">INDEPENDENT BY DESIGN</span><p>LL Collective Studio verbindet strategisches Marketing mit einer modernen visuellen Perspektive. Gegründet von Luis Fried und Leander Ballhausen.</p><p>Die Zusammenarbeit ist persönlich und direkt. Wir hören zu, stellen die richtigen Fragen und entwickeln daraus einen Auftritt, der zu Unternehmen, Zielgruppe und Vorhaben passt.</p><div className="founders"><div><span>01 / CO-FOUNDER</span><strong>Luis Fried</strong></div><div><span>02 / CO-FOUNDER</span><strong>Leander Ballhausen</strong></div></div></div></div></section>
  <section id="process" className="process-section section-pad"><div className="section-heading"><div><span className="eyebrow">05 / OUR PROCESS</span><h2>From first thought<br/>to <em>final impact.</em></h2></div><p>Ein klarer Ablauf lässt Raum für die Idee. Jede Phase bringt uns näher an einen Auftritt, der funktioniert.</p></div><div className="process-list">{[['01','Discover','Im Briefing klären wir Geschäftsziel, Zielgruppe und den bisherigen Auftritt.'],['02','Direction','Wir schärfen Positionierung und visuelle Richtung. Dabei halten wir Leistungsumfang (Scope) und konkrete Ergebnisse fest.'],['03','Create','Wir gestalten den Markenauftritt, die Website, Kampagne oder Inhalte.'],['04','Refine','Wir prüfen Details, arbeiten Feedback ein und verfeinern die Umsetzung.'],['05','Launch & Grow','Wir veröffentlichen, beobachten die Wirkung und entwickeln weiter.']].map(([n,title,desc]) => <div className="process-row reveal" key={n}><span>{n}</span><h3>{title}</h3><p>{desc}</p><ArrowUpRight size={20} strokeWidth={1}/></div>)}</div></section>
  <section id="contact" className="contact-section section-pad"><div className="contact-intro reveal"><span className="eyebrow">06 / CONTACT</span><h2>Ein guter Anfang<br/>ist ein <em>Gespräch.</em></h2><p>Ob eine konkrete Aufgabe oder eine erste Idee: Schreiben Sie uns, worum es geht. Wir nehmen uns Zeit für eine persönliche Rückmeldung.</p></div><div className="contact-invite reveal"><span className="eyebrow">DIREKTER KONTAKT</span><a className="contact-email" href={`mailto:${site.email}`}>{site.email}<ArrowUpRight size={27} strokeWidth={1.2}/></a><p>Eine kurze E-Mail reicht für den Anfang. Alles Weitere besprechen wir gemeinsam.</p><div className="contact-signature"><BrandMark/><span>LL COLLECTIVE STUDIO<br/>MUNICH / GERMANY</span></div></div></section>
  </main><Footer/><Motion/></>; }
