'use client';
import { useState } from 'react';
const steps = [
  { label: 'STRATEGIE', number: '01', question: 'Wofür steht Ihre Marke – und wen soll sie erreichen?', text: 'Wir betrachten Angebot, Zielgruppe und bisherigen Auftritt. Daraus entwickeln wir eine klare Positionierung und eine Botschaft, an der sich spätere Entscheidungen orientieren.', outputs: ['Zielgruppen und Bedürfnisse', 'Positionierung und Kernbotschaft', 'Prioritäten für den Markenauftritt'] },
  { label: 'DESIGN', number: '02', question: 'Wie wird diese Richtung sichtbar?', text: 'Eine konsistente Bildwelt, Typografie und Gestaltung übersetzt die Strategie in erkennbare Berührungspunkte – vom ersten Social-Post bis zur Website.', outputs: ['Visuelle Leitidee', 'Gestaltungssystem und Anwendungen', 'Wiedererkennbare Bildsprache'] },
  { label: 'CONTENT', number: '03', question: 'Was erzählen wir – und wo?', text: 'Wir legen Themen, Formate und Kanalrollen fest. So entsteht Content, der die Marke verständlich macht und sich im Alltag zuverlässig produzieren lässt.', outputs: ['Themen und Formate', 'Redaktionsrhythmus', 'Content für passende Kanäle'] },
  { label: 'ENTWICKLUNG', number: '04', question: 'Was wirkt, und was lernen wir daraus?', text: 'Wir legen Kennzahlen (KPIs) fest, die zum Geschäftsziel passen. Rückmeldungen und verfügbare Daten zeigen, welche Inhalte oder Maßnahmen wir anpassen sollten.', outputs: ['Klare Ziele und passende KPIs', 'Regelmäßige Auswertung', 'Konkrete nächste Schritte'] },
];
export function Growth() {
  const [active, setActive] = useState(0); const current = steps[active];
  return <section id="growth" className="growth-section section-pad"><div className="growth-head reveal"><span className="eyebrow">03 / GROWTH WITH DIRECTION</span><span className="growth-head-line"/></div><div className="growth-grid"><div className="reveal"><h2>Growth needs<br/><em>direction.</em></h2><p>Eine Marke wächst, wenn Positionierung, Gestaltung und Kommunikation zusammenarbeiten. Dafür braucht es erst eine klare Grundlage – und dann eine Umsetzung, die sich weiterentwickeln lässt.</p></div><div className="growth-visual reveal" aria-hidden="true"><div className="growth-ring ring-one"/><div className="growth-ring ring-two"/><div className="growth-center"><small>THE COLLECTIVE<br/>APPROACH</small><strong>{current.number}</strong><span>{current.label}</span></div></div></div><div className="growth-steps reveal" role="group" aria-label="Vier Schritte für einen konsistenten Markenauftritt">{steps.map((step, i) => <button key={step.label} className={active === i ? 'active' : ''} onMouseEnter={() => setActive(i)} onFocus={() => setActive(i)} onClick={() => setActive(i)} aria-pressed={active === i}><span>{step.number} / 04</span>{step.label}</button>)}</div><div className="growth-explainer" aria-live="polite" key={current.number}><div><span className="eyebrow">DIE ENTSCHEIDENDE FRAGE</span><h3>{current.question}</h3><p>{current.text}</p></div><div className="growth-output"><span className="eyebrow">WAS DARAUS ENTSTEHEN KANN</span>{current.outputs.map((item, i) => <div className="growth-output-row" key={item}><span>0{i + 1}</span><strong>{item}</strong></div>)}</div></div><div className="growth-conclusion reveal"><span>KLARHEIT → KONSISTENZ → WEITERENTWICKLUNG</span><p>Wir versprechen keine erfundenen Zahlen. Wir arbeiten mit einer nachvollziehbaren Richtung und prüfen gemeinsam, was zu Ihrer Marke und Ihren Zielen passt.</p></div></section>;
}
