export const site = {
  name: 'LL Collective Studio', location: 'Munich / Germany',
  email: 'LLCollectiveStudio@gmail.com', instagram: '', linkedin: '',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://ll-collective-studio-preview.luis-julian-fried.chatgpt.site',
};
export const showcases = [
  { number: '01', title: 'Eine Marke mit Profil.', category: 'BRAND STRATEGY & IDENTITY', tone: 'amber', visual: 'identity', description: 'Wir schärfen Positionierung und Nutzenversprechen (Value Proposition). Daraus entsteht eine visuelle Sprache, die an wichtigen Kontaktpunkten – den Touchpoints – wiedererkennbar bleibt.', deliverables: ['Positionierung und Markenstory', 'Logo und visuelles System', 'Anwendungsbeispiele und Guidelines'], outcome: 'Eine klare Grundlage für alles, was Ihre Marke als Nächstes zeigt.' },
  { number: '02', title: 'Content mit Richtung.', category: 'SOCIAL MEDIA & CONTENT', tone: 'silver', visual: 'social', description: 'Ein zusammenhängender Auftritt statt einzelner Posts: feste Themenfelder (Content Pillars), passende Formate und eine einheitliche Tonalität (Tone of Voice) greifen ineinander.', deliverables: ['Content Pillars und Redaktionsplan', 'Reels, Bildsprache und Gestaltung', 'Kanalübergreifende Formate'], outcome: 'Inhalte, die zur Marke passen und regelmäßig umgesetzt werden können.' },
  { number: '03', title: 'Digital, das bleibt.', category: 'WEB DESIGN & EXPERIENCE', tone: 'blue', visual: 'web', description: 'Eine Website soll das Angebot schnell verständlich machen. Dafür gestalten wir einen klaren User Flow – den Weg vom ersten Eindruck bis zur gewünschten Handlung.', deliverables: ['Struktur und Nutzerführung (UX)', 'Responsive Webdesign', 'Designsystem für konsistente Seiten', 'Interaktion und Motion'], outcome: 'Ein digitaler Auftritt, der Menschen informiert und die gewünschte Handlung – die Conversion – erleichtert.' },
  { number: '04', title: 'Ideen, die weitertragen.', category: 'CAMPAIGNS & GROWTH', tone: 'violet', visual: 'campaign', description: 'Eine Kampagne braucht eine klare Kernbotschaft (Key Message) und ein wiedererkennbares Leitmotiv (Key Visual). Der Kanalmix verbindet beides mit den passenden Orten und Formaten für die Zielgruppe.', deliverables: ['Kampagnenidee und Botschaft', 'Leitmotiv und Assets für Kanäle', 'Kanalmix, Auswertung und Anpassung'], outcome: 'Ein Konzept, das über ein einzelnes Motiv hinaus funktioniert.' },
  { number: '05', title: 'Erlebnisse mit Nachhall.', category: 'EVENT MARKETING & PR', tone: 'olive', visual: 'event', description: 'Wir denken ein Event als zusammenhängendes Erlebnis – von der Einladung bis zum Content danach. In der PR kann ergänzend Earned Media entstehen: Aufmerksamkeit durch unabhängige Berichterstattung.', deliverables: ['Eventidentität und Kommunikation', 'Social-Begleitung vor Ort', 'Content und Nachbereitung'], outcome: 'Ein Moment, der auch nach dem Veranstaltungstag sichtbar bleibt.' },
] as const;
export const services = [
  { title: 'Brand Strategy & Identity', subtitle: 'Eine Marke braucht eine Richtung.', description: 'Wir klären Positionierung, Zielgruppe und Nutzenversprechen. Darauf bauen Identität und visuelle Sprache auf.', items: 'Positionierung · Zielgruppen · Identität · Gestaltungssystem' },
  { title: 'Social Media & Content', subtitle: 'Inhalte mit einem Gedanken dahinter.', description: 'Wiederkehrende Themen, passende Formate und ein realistischer Redaktionsplan halten den Auftritt konsistent.', items: 'Strategie · Redaktion · Foto & Video · Kampagnen' },
  { title: 'Web Design & Digital', subtitle: 'Ein Auftritt, der weiterführt.', description: 'Eine klare Seitenstruktur und Nutzerführung machen das Angebot verständlich und führen zu sinnvollen nächsten Schritten.', items: 'Konzeption · UX · Websites · Motion' },
  { title: 'Campaigns & Growth', subtitle: 'Kreativität mit klarer Absicht.', description: 'Wir verbinden Kampagnenidee und Botschaft mit einem definierten Ziel und prüfen, welche Maßnahmen wirken.', items: 'Leitidee · Kanäle · Optimierung · Auswertung' },
  { title: 'Event Marketing & PR', subtitle: 'Momente, die bleiben.', description: 'Vom Konzept bis zur Kommunikation vor, während und nach einem Event entsteht ein zusammenhängendes Markenerlebnis.', items: 'Eventkonzept · Kommunikation · Content · PR' },
];
